services:
  server:
    build:
      context: ./apps/server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./apps/server/app:/app/app
    env_file:
      - ./apps/server/.env
    depends_on:
      - db

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000/api
    volumes:
      - ./apps/web:/app
    depends_on:
      - server

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lintao123
      MYSQL_DATABASE: graph
      MYSQL_USER: jack
      MYSQL_PASSWORD: ''
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
